mysql: &mysql
  adapter: mysql2

defaults: &defaults
  pool: <%= ENV['CONCURRENCY'].to_i + 5 %>
  timeout: 5000
  wait_timeout: 1800
  encoding: utf8mb4
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>

  <<: *mysql

development:
  primary:
    <<: *defaults

  enrichments:
    adapter: sqlite3
    database: db/enrichments.sqlite3

test:
  # <<: *defaults
  adapter: nulldb
  # database: <%= ENV['MYSQL_DATABASE'] %>_test<%= ENV['TEST_ENV_NUMBER'] %>
  enrichments:
    adapter: sqlite3
    database: db/enrichments.sqlite3

production:
  <<: *defaults

stage:
  primary:
    <<: *defaults

  enrichments:
    adapter: sqlite3
    database: db/enrichments.sqlite3

uat:
  <<: *defaults
